quarkus:
  datasource:
    devservices:
      port: 5432

mp:
  messaging:
    outgoing:
      packaging:
        connector: smallrye-rabbitmq
        exchange:
          name: orders
        routing-key: orders.packaging
    incoming:
      packager:
        connector: smallrye-rabbitmq
        queue:
          name: orders.packaging
        exchange:
          name: orders
        routing-key: orders.packaging

"%test":
  mp:
    messaging:
      incoming:
        packager:
          enabled: false
        packaging-test:
          connector: smallrye-rabbitmq
          queue:
            name: orders.packaging.test
          exchange:
            name: orders
          routing-key: orders.packaging
